# Version 0.0.3
# This version builds a spigot server
# using the recommended build strategy for spigot
# This is advantageous in that it’s better for plugin development
# and fits well with the Docker approach
#
FROM ubuntu:16.04
MAINTAINER Kyle Brown “brownkyl@us.ibm.com”
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y default-jdk
RUN apt-get install -y wget
RUN apt-get install -y vim
RUN mkdir minecraft
RUN wget "https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar" -O minecraft/BuildTools.jar
RUN git config --global core.autocrlf input
RUN java -jar minecraft/BuildTools.jar --rev 1.11.2
RUN cp spigot-1.11.2.jar spigot.jar
RUN echo "eula=true" > eula.txt
# Install plugins from Andy Hunt's 'Learn to Program with Minecraft Plugins'
RUN wget http://media.pragprog.com/titles/ahmine/code/ahmine-code.tgz && tar xfz ahmine-code.tgz
# Replace bukkit.jar with spigot.jar in build.sh
RUN find code -name build.sh -exec sed -ie 's/bukkit.jar/spigot.jar/g' {} \;
ENV MCSERVER /
WORKDIR /code/HelloWorld
RUN ./build.sh
WORKDIR /
CMD java -XX:MaxPermSize=128M -Xms512m -Xmx1024m -jar spigot.jar nogui
EXPOSE 25565
